### ISSUE TITLE
Задание 2

### ISSUE THREAD

**Issue by d-qql** [SuppFear/Dense-CSR#1]
1) Очень странные графики для сильно заполненных матриц, выглядит не правдоподобно.

2) Не вижу конструктора для CSR матрицы

3) Пройтись по https://github.com/MIPT-SLE/UnforgivableCurses и убрать все запрещенное из кода

**Comment by SuppFear** [comment]
1. ![plot_dense](https://github.com/SuppFear/Dense-CSR/assets/113615853/2e4fe26d-1bf8-412f-bf8b-98730a9b2c20) - исправена ошибка в коде для построения графиков
2. Констурктор объявлен в csr_matrix.h и реализован csr_matrix.cpp
3. Ничего запрещенного в коде нет (все запрещенное закомментировано)
